
obj-m := lkd_test_cdev.o

# KDIR := /home/marc/Work/7108/kernel/
# PWD := $(shell pwd)
#all: clean modules
#modules install modules_install:
#	$(MAKE) -C $(KDIR) M=$(PWD) $@ 


clean:
	rm -fr .*.cmd .tmp_versions *.symvers *.o *.ko *.mod.c *.order
