#!/bin/sh

PATH=/bin/:/sbin/:$PATH

if [ -z $1  ]
then
	echo "please provide a module name"
	exit 2
fi

module="$1"
device="$1_dev"
mode="664"
rmmod $module 2> /dev/null
# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
insmod ./$module.ko || exit 1
# remove stale nodes
rm -f /dev/${device}
major=$(sed -n "s/^[ ]*\([0-9]*\)[ ]*$module$/\1/p" /proc/devices)
mknod /dev/${device} c $major 0

# give appropriate group/permissions, and change the group.
# Not all distributions have staff, some have "wheel" instead.
group="staff"
grep -q '^staff:' /etc/group || group="wheel"
chgrp $group /dev/${device}
chmod $mode /dev/${device}

